#!/bin/bash
set -e
exec 2>>/tmp/jog_error.log

# Renders dnsmasq config so DHCP only binds to the USB imaging NIC (TFTP is FOG’s tftpd on :69).
# Requires /etc/jog/jog.env (see config/jog.env.example).

ERROR_LOG="/tmp/jog_error.log"
log() { echo "JOG-DNSMASQ: $*"; }
err() { echo "JOG-DNSMASQ-ERROR: $*" | tee -a "$ERROR_LOG" >&2; }

JOG_ENV="${JOG_ENV:-/etc/jog/jog.env}"
if [[ ! -f "$JOG_ENV" ]]; then
  err "Missing $JOG_ENV (copy from JOG/config/jog.env.example)"
  exit 1
fi
# shellcheck disable=SC1090
source "$JOG_ENV"

: "${JOG_USB_IFACE:?Set JOG_USB_IFACE in $JOG_ENV}"
: "${JOG_DHCP_START:?}"
: "${JOG_DHCP_END:?}"
: "${JOG_DHCP_NETMASK:?}"
: "${JOG_DHCP_LEASE_HOURS:?}"
: "${JOG_NEXT_SERVER:?}"
: "${JOG_DHCP_ROUTER:?}"

OUT="${1:-/etc/dnsmasq.d/99-jog-imaging.conf}"
mkdir -p "$(dirname "$OUT")"

# bind-interfaces + explicit interface= ensures dnsmasq does not open DHCP on onboard NIC or WiFi.
cat >"$OUT" <<EOF
# Generated by jog-render-dnsmasq.sh — do not edit by hand.
# USB imaging NIC only:
interface=${JOG_USB_IFACE}
bind-interfaces
except-interface=lo

# DHCP for PXE clients on the imaging cable only
dhcp-range=${JOG_DHCP_START},${JOG_DHCP_END},${JOG_DHCP_NETMASK},${JOG_DHCP_LEASE_HOURS}h
dhcp-option=option:router,${JOG_DHCP_ROUTER}
dhcp-option=option:dns-server,${JOG_NEXT_SERVER}

# NEXT SERVER + PXE boot file — TFTP is served by FOG (tftpd-hpa from /opt/fog install), not dnsmasq,
# so UDP/69 is not double-bound. Override filename for BIOS vs UEFI if needed.
dhcp-option=option:tftp-server,${JOG_NEXT_SERVER}
dhcp-boot=${JOG_DHCP_BOOTFILE:-snponly.efi},${JOG_NEXT_SERVER}
EOF

log "Wrote $OUT (interface=${JOG_USB_IFACE})"
